version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - flagman-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  flagman-back:
    #build: .
    ports:
      - "8080:8080"
    image: c0dys/flagman-back
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONFIG_PATH=/app/config/local.yaml
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - flagman-network

networks:
  flagman-network:
    driver: bridge
