import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";
import { User } from "lucide-react";
import NavBar from "@/widgets/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userId = cookieStore.get("user_id");
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {userId && (
          <Link
            href={`/user/${userId?.value}`}
            className="z-10 rounded-[100%] absolute transform translate-[-50%,-50%] right-[5%] top-[3%] w-10 h-10 flex justify-center items-center bg-gradient-to-r from-blue-500 to-purple-600 "
          >
            <User color="white" />
          </Link>
        )}
        <main className="min-h-screen max-w-screen  bg-gray-100">
          {children}
        </main>
        <NavBar />
      </body>
    </html>
  );
}
